# Generated by Django 5.0 on 2023-12-26 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='resumen',
            field=models.TextField(blank=True, null=True),
        ),
    ]
