# Generated by Django 5.0 on 2023-12-26 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0002_articulo_resumen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='resumen',
            field=models.TextField(blank=True, default='Valor predeterminado', null=True),
        ),
    ]
