# Generated by Django 5.0 on 2023-12-29 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0004_remove_articulo_resumen'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='articulos_imagenes/'),
        ),
    ]
