# Generated by Django 5.0 on 2023-12-30 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0006_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='categoria',
            field=models.CharField(choices=[('tecnologia', 'Tecnología'), ('gastronomia', 'Gastronomía'), ('artesanias', 'Artesanías'), ('entretenimiento', 'Entretenimiento'), ('salud', 'Salud y Bienestar')], default='tecnologia', max_length=20),
        ),
    ]
