# Generated by Django 5.0 on 2023-12-30 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0007_articulo_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='categoria',
            field=models.CharField(blank=True, choices=[('tecnologia', 'Tecnología'), ('gastronomia', 'Gastronomía'), ('artesanias', 'Artesanías'), ('entretenimiento', 'Entretenimiento'), ('salud', 'Salud y bienestar')], max_length=20, null=True),
        ),
    ]
